language: python
python:
  - "3.6"
before_install:
    - sudo rm -f /etc/boto.cfg
    - sudo apt-get -qq update
    - sudo apt-get install -y make
    - pip install -r requirements_dev.txt
    - pip install coveralls
script:
  - make
  - coveralls
